### Search for an offender
POST {{host}}/paged-search?
    page={{$random.integer(100)}}&
    pageSize={{$random.integer(100)}}
Authorization: Bearer {{$auth.token("token")}}
Content-Type: application/json

{
  "crn": "{{crn}}",
  "firstName": "{{ offenderSearch.firstName }}",
  "lastName": "{{ offenderSearch.lastName }}"
}