-- The NOMIS values below were taken from calling:
-- https://prison-register.hmpps.service.justice.gov.uk/swagger-ui/index.html#/prison-resource/getPrisonNames

-- The PPUD ones were provided by someone from the PPUD team. They
-- were mapped manually and the mapping was checked with the PPCS team.

INSERT INTO nomis_to_ppud_establishment_mapping
VALUES ('ACI', 'HMP Altcourse'),
       ('ASI', 'HMP/YOI Ashfield'),
       ('AGI', 'HMP/YOI Askham Grange'),
       ('AYI', 'HMP/YOI Aylesbury'),
       ('BFI', 'HMP Bedford'),
       ('BAI', 'HMP Belmarsh'),
       ('BWI', 'HMP Berwyn'),
       ('BMI', 'HMP Birmingham'),
       ('BSI', 'HMP/YOI Brinsford'),
       ('BLI', 'HMP Bristol'),
       ('BXI', 'HMP Brixton'),
       ('BZI', 'HMP/YOI Bronzefield'),
       ('BCI', 'HMP Buckley Hall'),
       ('BNI', 'HMP Bullingdon'),
       ('BRI', 'HMP Bure'),
       ('CFI', 'HMP Cardiff'),
       ('CWI', 'HMP Channings Wood'),
       ('CDI', 'HMP/YOI Chelmsford'),
       ('CLI', 'HMP Coldingley'),
       ('CKI', 'HMYOI Cookham Wood'),
       ('DAI', 'HMP Dartmoor'),
       ('DTI', 'HMYOI Deerbolt'),
       ('DNI', 'HMP/YOI Doncaster'),
       ('DGI', 'HMP Dovegate'),
       ('DWI', 'HMP/YOI Downview'),
       ('DHI', 'HMP/YOI Drake Hall'),
       ('DMI', 'HMP Durham'),
       ('ESI', 'HMP/YOI East Sutton Park'),
       ('EWI', 'HMP/YOI Eastwood Park'),
       ('EYI', 'HMP/YOI Elmley'),
       ('EEI', 'HMP Erlestoke'),
       ('EXI', 'HMP/YOI Exeter'),
       ('FSI', 'HMP Featherstone'),
       ('FYI', 'HMYOI Feltham'),
       ('FMI', 'HMYOI Feltham'),
       ('FWI', 'HMP Five Wells'),
       ('FDI', 'HMP Ford'),
       ('FBI', 'HMP/YOI Forest Bank'),
       ('FEI', 'HMP Fosse Way'),
       ('FHI', 'HMP/YOI Foston Hall'),
       ('FKI', 'HMP Frankland'),
       ('FNI', 'HMP Full Sutton'),
       ('GHI', 'HMP Garth'),
       ('GTI', 'HMP Gartree'),
       ('GNI', 'HMP Grendon'),
       ('GMI', 'HMP Guys Marsh'),
       ('HDI', 'HMYOI Hatfield (formerly Moorland Open)'),
       ('HVI', 'HMP Haverigg'),
       ('HEI', 'HMP Hewell'),
       ('HOI', 'HMP/YOI High Down'),
       ('HPI', 'HMP Highpoint'),
       ('HII', 'HMP/YOI Hindley'),
       ('HBI', 'HMP/YOI Hollesley Bay'),
       ('HHI', 'HMP Holme House'),
       ('HLI', 'HMP Hull'),
       ('HMI', 'HMP Humber'),
       ('HCI', 'HMP Huntercombe'),
       ('ISI', 'HMP/YOI Isis'),
       ('IWI', 'HMP Isle of Wight'),
       ('KMI', 'HMP Kirkham'),
       ('KVI', 'HMP Kirklevington Grange'),
       ('LFI', 'HMP/YOI Lancaster Farms'),
       ('LEI', 'HMP Leeds'),
       ('LCI', 'HMP Leicester'),
       ('LWI', 'HMP/YOI Lewes'),
       ('LYI', 'HMP Leyhill'),
       ('LII', 'HMP Lincoln'),
       ('LHI', 'HMP Lindholme'),
       ('LTI', 'HMP Littlehey'),
       ('LPI', 'HMP Liverpool'),
       ('LLI', 'HMP Long Lartin'),
       ('LGI', 'HMP Lowdham Grange'),
       ('LNI', 'HMP/YOI Low Newton'),
       ('MSI', 'HMP Maidstone'),
       ('MRI', 'HMP Manchester'),
       ('MDI', 'HMP/YOI Moorland Closed'),
       ('MHI', 'HMP Morton Hall'),
       ('NHI', 'HMP/YOI New Hall'),
       ('NSI', 'HMP North Sea Camp'),
       ('NLI', 'HMP Northumberland'),
       ('NWI', 'HMP/YOI Norwich'),
       ('NMI', 'HMP Nottingham'),
       ('STC3', 'Oakhill (STC)'),
       ('OWI', 'HMP Oakwood'),
       ('ONI', 'HMP Onley'),
       ('PRI', 'HMP/YOI Parc'),
       ('PYI', 'HMP/YOI Parc'),
       ('PVI', 'HMP Pentonville'),
       ('PFI', 'HMP Peterborough'),
       ('PBI', 'HMP Peterborough'),
       ('PDI', 'HMYOI Portland'),
       ('UPI', 'HMP/YOI Prescoed'),
       ('PNI', 'HMP Preston'),
       ('RNI', 'HMP Ranby'),
       ('RSI', 'HMP Risley'),
       ('RCI', 'HMP/YOI Rochester'),
       ('RHI', 'HMP Rye Hill'),
       ('SDI', 'HMP Send'),
       ('SPI', 'HMP Spring Hill'),
       ('SFI', 'HMP Stafford'),
       ('EHI', 'HMP Standford Hill'),
       ('SKI', 'HMP Stocken'),
       ('SHI', 'HMP/YOI Stoke Heath'),
       ('STI', 'HMP/YOI Styal'),
       ('SUI', 'HMP Sudbury'),
       ('SLI', 'HMP Swaleside'),
       ('SWI', 'HMP Swansea'),
       ('SNI', 'HMP/YOI Swinfen Hall'),
       ('TSI', 'HMP Thameside'),
       ('MTI', 'HMP The Mount'),
       ('VEI', 'HMP The Verne'),
       ('TCI', 'HMP/YOI Thorn Cross'),
       ('UKI', 'HMP Usk'),
       ('WDI', 'HMP Wakefield'),
       ('WWI', 'HMP Wandsworth'),
       ('WII', 'HMP Warren Hill'),
       ('WLI', 'HMP Wayland'),
       ('WEI', 'HMP Wealstun'),
       ('WNI', 'HMYOI Werrington'),
       ('WYI', 'HMYOI Wetherby'),
       ('WTI', 'HMP Whatton'),
       ('WRI', 'HMP Whitemoor'),
       ('WCI', 'HMP Winchester'),
       ('WHI', 'HMP Woodhill'),
       ('WSI', 'HMP Wormwood Scrubs'),
       ('WMI', 'HMP Wymott')