generic-service:
  nameOverride: make-recall-decision-api
  serviceAccountName: make-recall-decision

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/make-recall-decision-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: make-recall-decision-cert
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      nginx.ingress.kubernetes.io/limit-rpm: "200"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "300"

  livenessProbe:
    httpGet:
      path: /health/liveness
      port: http
  readinessProbe:
    httpGet:
      path: /health
      port: http

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "default"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SENTRY_DSN: https://d51aaaaf56b547b8b0582ed0af80bdb7@o345774.ingest.sentry.io/6361157
    GOTENBERG_ENDPOINT_URL: http://make-recall-decision-api-gotenberg
    HMPPS_SQS_USE_WEB_TOKEN: "true"
    SPRING_DATA_REDIS_SSL_ENABLED: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    make-recall-decision-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    make-recall-decision-api-database:
      POSTGRES_HOST: "host"
      POSTGRES_DBNAME: "name"
      POSTGRES_USERNAME: "username"
      POSTGRES_PASSWORD: "password"
    hmpps-domain-events-topic:
      HMPPS_DOMAIN_EVENT_TOPIC_ARN: "topic_arn"
    elasticache-redis:
      SPRING_DATA_REDIS_HOST: "primary_endpoint_address"
      SPRING_DATA_REDIS_PASSWORD: "auth_token"
    make-recall-decision-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

  allowlist:
    north_shields_user: 194.33.192.1/24
    kettering_user: 194.33.196.4/24
    ark-dom1-farnborough: 194.33.192.0/24
    ark-dom1-corsham: 194.33.196.0/24
    groups:
      - internal
      - prisons
      - private_prisons

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /prometheus
    metricsPort: 8080

generic-prometheus-alerts:
  targetApplication: make-recall-decision-api
